---
title: "Lichess Bullet Chess Analysis"
author: "Hiroki Yagi"
date: "`r lubridate::today()`"
echo: false
output-format: pdf
format:
  html:
    code-fold: true
    df-print: kable
    toc: true
    number-sections: true
  pdf:
    df-print: kable
    toc: true
    number-sections: true
    documentclass: ltjsarticle
    pdf-engine: lualatex
---

## データの準備

### オープニングデータ

### ゲームのデータ

TODO: 日付の変更。おそらくtimestamp

lichess api のデータが2024-6-15あたりで変わっている(columnが追加されたっぽい)
どかこのタイミングでlichessのゲームデータにカラムが追加されたみたい。> colnames(tmp1)
```{text}
[1] "id"                       "rated"
 [3] "variant"                  "speed"
 [5] "perf"                     "createdAt"
 [7] "lastMoveAt"               "status"
 [9] "source"                   "fullId"
[11] "winner"                   "players.white.rating"
[13] "players.white.ratingDiff" "players.white.user.name"
[15] "players.white.user.id"    "players.black.rating"
[17] "players.black.ratingDiff" "players.black.user.name"
[19] "players.black.user.id"    "opening.eco"
[21] "opening.name"             "opening.ply"
[23] "clock.initial"            "clock.increment"
[25] "clock.totalTime"          "color"
[27] "win"
> colnames(tmp2)
 [1] "id"                        "rated"
 [3] "variant"                   "speed"
 [5] "perf"                      "createdAt"
 [7] "lastMoveAt"                "status"
 [9] "source"                    "fullId"
[11] "winner"                    "players.white.rating"
[13] "players.white.ratingDiff"  "players.white.user.name"
[15] "players.white.user.id"     "players.black.rating"
[17] "players.black.ratingDiff"  "players.black.user.name"
[19] "players.black.user.id"     "opening.eco"
[21] "opening.name"              "opening.ply"
[23] "clock.initial"             "clock.increment"
[25] "clock.totalTime"           "players.black.user.flair"
[27] "players.white.user.flair"  "players.black.user.patron"
[29] "players.white.user.patron" "color"
[31] "win"
```


```{r}
#| include: false
library(tidyverse)
library(ggplot2)
library(targets)
library(kableExtra)
targets::tar_load(data)


print_win_rate_table <- function(data) {
  data |>
    mutate(
      winrate = sprintf("%.3f", round(winrate, 3))
    ) |>
    kbl(escape = FALSE) |> kable_styling() |>
    column_spec(4, color = "white",
      background = spec_color(data$winrate, option = "B", scale_from = c(0, 1))
    )
}


```

## 戦形別の勝率??

ゲーム数が`r tar_read(min_game_number)`を越えるものに限ったyo

### white

白番での成績は @tbl-white-score のようになった。

```{r}
#| label: tbl-white-score
#| tbl-cap: "Opening Score: White"
tar_read(white_opening_winrate) |> print_win_rate_table()
```

{{< pagebreak >}}

### black

黒番での成績は @tbl-black-score のようになった。

```{r}
#| label: tbl-black-score
#| tbl-cap: "Opening Score: Black"
tar_read(black_opening_winrate) |> print_win_rate_table()
```

<!-- ```{r} -->
<!-- tar_read(black_opening_winrate) |> inner_join(tar_read(opening_data), by = c("opening.name" = "name")) -->
<!-- ``` -->
